stages:
  - init
  - test
  - build
  - deploy
init:
  index: 0
  stage: init
  type: init

clone:
  index: 1
  stage: init
  type: clone
  
shell0:
  index: 1
  stage: test
  type: shell
  config:
    script: echo 你好，测试阶段 

shell1:
  index: 0
  stage: build
  type: shell
  config:
    script: echo 你好，构建阶段 

shell2:
  index: 0
  stage: deploy
  type: shell
  config:
    script: echo 你好，部署阶段
clean:
  index: 1
  stage: deploy
  type: clean