stages:
  - init
  - test
  - build
  - deploy

init:
  index: 0
  stage: init
  type: init

clone:
  index: 1
  stage: init
  type: clone

test:
  index: 0
  stage: test
  type: test
  config:
    dockerfile: Dockerfile.test

shell1:
  index: 0
  stage: build
  type: shell
  config:
    script: echo 你好，构建阶段 

buildImage:
  index: 1
  stage: build
  type: buildRunningImage

# pushImage:
#   index: 2
#   stage: build
#   type: pushImage

shell2:
  index: 0
  stage: deploy
  type: shell
  config:
    script: echo 你好，部署阶段
